### ISSUE TITLE
Actions が失敗したときに Discord に通知が行くように

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#17]
- Discord の Webhook 機能を使用する
- lint のみでやる

- [x] embed でいい感じに情報をまとめる
- [ ] GitHub ユーザー名と Discord のユーザー ID を紐づけてメンションできるように

**Comment by TwoSquirrels** [comment]
優先順位低いけど気分転換にこれ先にやるか()

**Comment by Mogyuchi** [comment]
どうやろうとしてる？

**Comment by TwoSquirrels** [comment]
まぁ見とけって (は？)

**Comment by TwoSquirrels** [comment]
よさそうなやつみっけた
https://github.com/marketplace/actions/actions-status-discord
