### ISSUE TITLE
[要望]: 各種 SNS のフォローボタン

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#177]
### リクエスト

フッターに各種 SNS のフォローボタンを追加

- [x] [Twitter @uchikoshifes](https://twitter.com/uchikoshifes)
- [x] LINE (ClosedBeta のためここでは非公開)
- [x] [Youtube](https://youtube.com/channel/UCIfMXvUdm7UiFLBmV8ZmQcA)
- [x] [Instagram @uchikoshifes](https://instagram.com/uchikoshifes)

**Comment by TwoSquirrels** [comment]
これのためにフッターのレイアウトちょっと変えなきゃか？

**Comment by gendaineko2222** [comment]
個人的にはアイコンだけのほうがかっこいいと思う

**Comment by TwoSquirrels** [comment]
気付きにくくなりそう
多少は主張したいかな

**Comment by gendaineko2222** [comment]
文字だけのほうが目立ちにくい気がする…
拾ってきたやつだけど↓みたいな感じにすれば和モダンっていうテーマにもあっていいと思います
白と黒を基調としたデザインの中に和風な色のボタンとかタイル型のグリッドレイアウト？を入れるのが手早く和モダンな感じが出るんじゃないかなとイメージしてます
りすりすさんの全体的な完成イメージがあれば教えて欲しいです
(discussionsのデザインどうするの問題のとこでやったほうが良さそうなのでそっちにも書いときます)
![image](https://user-images.githubusercontent.com/93499945/183292113-421a4e5b-9161-4329-b311-3c546fa76046.png)

**Comment by gendaineko2222** [comment]
とりあえず文字だけ(現状維持)でもokです

**Comment by TwoSquirrels** [comment]
アイコン + 文字 を考えてる

**Comment by gendaineko2222** [comment]
なるほど
