### ISSUE TITLE
[要望]: フロアマップページ

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#216]
### リクエスト

画像を置いて、文字の位置は % で指定して、クリックで部屋情報 (簡易) までスクロール、その中のリンクで団体ページに

**Comment by TwoSquirrels** [comment]
# マップ画像 (パンフレットのスクリーンショットを加工したもの)
## 全体
![index](https://media.discordapp.net/attachments/947306584546103370/1015298213844095108/unknown.png)
## 本館
### １階
![main-f1](https://media.discordapp.net/attachments/947306584546103370/1015275813911941190/unknown.png)
### ２階
![main-f2](https://media.discordapp.net/attachments/947306584546103370/1015279474721443923/unknown.png)
## 中学棟
### １階
![jhs-f1](https://media.discordapp.net/attachments/947306584546103370/1015275367499583498/unknown.png)
### ２階
![jhs-f2](https://media.discordapp.net/attachments/947306584546103370/1015278511289806859/unknown.png)
### ３階
![jhs-f3](https://media.discordapp.net/attachments/947306584546103370/1015281203194109952/unknown.png)
### ４階
![jhs-f4](https://media.discordapp.net/attachments/947306584546103370/1015281990448189470/unknown.png)
### ５階
![jhs-f5](https://media.discordapp.net/attachments/947306584546103370/1015282872195743815/unknown.png)
## 高校棟

**Comment by Mogyuchi** [comment]
svgじゃないの；；

**Comment by Mogyuchi** [comment]
adobe製品だったらsvg出力できそう…

**Comment by TwoSquirrels** [comment]
できるだろうけど多分整理するの大変そう......

**Comment by TwoSquirrels** [comment]
元データ誰が持ってるかもわからないし()
