### ISSUE TITLE
Issue フォーム導入

### ISSUE THREAD

**Issue by Mogyuchi** [uchikoshi-fes/uchikoshi-fes.jp-2022#22]

**Comment by TwoSquirrels** [comment]
いるかな...

**Comment by Mogyuchi** [comment]
~~説明書いてないこういう Issueを作れなくなるから要る~~
Issue あけたときに自動で Labels つくようにできるから管理が楽になるで

**Comment by Mogyuchi** [comment]
https://github.com/Mogyuchi/github-test/issues/new/choose みたいなかんじ

**Comment by Mogyuchi** [comment]
質問飛んでくる可能性あるのか
https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/blob/9ffcb4ac4d440ac915d52fe9b6cf511e254d953e/README.md?plain=1#L42

**Comment by TwoSquirrels** [comment]
あー便利だな

**Comment by Mogyuchi** [comment]
`その他`用のやつ要るかな
Don’t see your issue here? [Open a blank issue.]()
って下に書いてあるんだけど。
![image](https://user-images.githubusercontent.com/69337624/167249126-75bc7db1-6c92-4460-8788-b0ae64fd8fb6.png)

**Comment by TwoSquirrels** [comment]
うーんわかりにくいし、いるんじゃね

**Comment by Mogyuchi** [comment]
把握

**Comment by Mogyuchi** [comment]
つくります

**Comment by TwoSquirrels** [comment]
ありがたい

**Comment by Mogyuchi** [comment]
タイポ指摘用フォームつくるか

**Comment by TwoSquirrels** [comment]
いいねSORE

**Comment by Mogyuchi** [comment]
不適切な表現の指摘をどこですれば良いのかわからない

**Comment by Mogyuchi** [comment]
改善提案に投げることにした

**Comment by Mogyuchi** [comment]
name を三文字以上にしなくてはならないらしく
空白入れたらキモくなったので
![DA2D35FD-936D-4715-A477-1E8451D9A6EC](https://user-images.githubusercontent.com/69337624/167282989-2a022b28-6758-4e7e-967d-978fa5c7b486.jpeg)
絵文字のプレフィックスつけようかと思ったが
改善提案の絵文字をどうすれば良いのかわからなくて死亡

**Comment by TwoSquirrels** [comment]
後ろに括弧で英訳つけるとか
質問 (question)
みたいな
