### ISSUE TITLE
Actions の時間制限をなくす

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#25]
タイトルの通り 1 分を ~~2 分~~ 無制限にする
workflow を書き換えるだけ

**Comment by Mogyuchi** [comment]
制限いるのか？

**Comment by TwoSquirrels** [comment]
バグって止まらなくなったら怖いから

**Comment by Mogyuchi** [comment]
Actions のとこから止められるで

**Comment by TwoSquirrels** [comment]
それ、手動じゃん

**Comment by Mogyuchi** [comment]
どう怖いのかわからないや
無駄に六時間動き続けるというのは手動で止められるから回避できる

**Comment by Mogyuchi** [comment]
privateリポジトリだったらActionsの実行時間に制限あるからタイムアウト指定しておくべきだと思うけど...

**Comment by TwoSquirrels** [comment]
public リポジトリって制限時間ないんだっけ

**Comment by TwoSquirrels** [comment]
ないのか、じゃあ制限時間取っ払おう
