### ISSUE TITLE
[改善]: サイズ調整の画像最適化を活用する

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#251]
### 改善対象の事柄

画像の大きさが指定されず無駄にでかい画像がダウンロードされてしまう。

### 期待する挙動

丁度いい大きさの画像をダウンロードする

**Comment by Mogyuchi** [comment]
んー？
正しく機能しているっぽい

**Comment by Mogyuchi** [comment]
https://uchikoshi-fes.jp/orgs
ここはダメだな
100vw が適用されている
