### ISSUE TITLE
[Bug]: 相対パスの画像が表示されない

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#255]
### URL

https://uchikoshi-fes.jp/orgs/apc

### 現在の状況

相対パスで指定されている画像が、imgix に渡す際に絶対パスとして認識されてしまい読み込まれない

### 期待する挙動

画像がちゃんと全部読み込まれる

### OS

Windows

### ブラウザ

Firefox

**Comment by Mogyuchi** [comment]
やります
