### ISSUE TITLE
[改善]: ファビコン

### ISSUE THREAD

**Issue by Mogyuchi** [uchikoshi-fes/uchikoshi-fes.jp-2022#263]
### 改善対象の事柄

ファビコンない

### 期待する挙動

ファビコンある

**Comment by TwoSquirrels** [comment]
Twitter のアイコンにするか

**Comment by Mogyuchi** [comment]
蝶のとこ切り出せませんかね

あ、自分でやれば良いのか

**Comment by Mogyuchi** [comment]
元ファイル手に入れられるなら渡してもらえると助かる

**Comment by TwoSquirrels** [comment]
https://media.discordapp.net/attachments/944805427139465306/1019857280373633034/5fc3467f8a0fe424.png
