### ISSUE TITLE
[改善]: next-optimized-images を使わないようにする

### ISSUE THREAD

**Issue by Mogyuchi** [uchikoshi-fes/uchikoshi-fes.jp-2022#33]
### 改善対象の事柄

`next-optimized-images` 及びそれに関連するパッケージ
- audit で警告が出る
- GPL-3.0+ でライセンスされているパッケージへ依存している

### 期待する挙動

`next-optimized-images` 及びそれに関連するパッケージに依存しなくなる

### 補足情報

#18 ができるまで画像が最適化されなくなります。

**Comment by TwoSquirrels** [comment]
じ！
