### ISSUE TITLE
[DX]: メジャーエディタ / IDE 用のファイルを作成

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#37]
### 改善対象の事柄

特定のエディタ / IDE で Git を使う際にそれ専用のファイルを
.gitignore を書き換えず (関係のないコミットはできないため) ステージングするのを避けるという
余計な操作が必要

### 期待する挙動

ほとんどのエディタ / IDE で `git add --all` するだけでいいように

### 補足情報

- [ ] `/.gitignore` に VS Code と IntelliJ IDEA 用の設定を追記
- [ ] VS Code 用に `/.vscode/` ディレクトリにファイルを追加
- [ ] IntelliJ IDEA 用に `/.idea/` ディレクトリを作成
- [ ] Replit 用に `/.replit` ファイルを作成
- [ ] `/DEVELOP.md` にこれらのファイルに関しての説明を追記

**Comment by TwoSquirrels** [comment]
わざと Git の管理下から手動で外さないといけないてきな？

**Comment by Mogyuchi** [comment]
gitignore したら #8 機能しなくなるんだが...

**Comment by TwoSquirrels** [comment]
いや、関係ないコミットを防ぐ為に、 git add をしないようにしなくちゃならないから、
それをそれの対策的な

**Comment by Mogyuchi** [comment]
あー理解

**Comment by TwoSquirrels** [comment]
やらないことにした
git 的にこれは各自でやるもんな気がする

**Comment by Mogyuchi** [comment]
EditorConfig 使ってみよう
