### ISSUE TITLE
[DX]: production 環境で husky などがインストールされずエラーになる

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#40]
### 改善対象の事柄

`NODE_ENV=production` 環境にて `pnpm install` を行うと devDependencies は入らないため、 prepare 実行時に husky が入っていないことでエラーになる
また、 npm-run-all も入っていないためエラーとなる

### 期待する挙動

プロダクション環境でエラーにならない

### 補足情報

`NODE_ENV=production` 環境下で husky を dependencies にするか、 prepare を実行しないようにするか
また、 npm-run-all を devDependencies から dependencies に移動

**Comment by Mogyuchi** [comment]
DX ではないな()

**Comment by Mogyuchi** [comment]
try `--ignore-scripts true`

**Comment by TwoSquirrels** [comment]
bug はサイト本体に関することだからね()

**Comment by Mogyuchi** [comment]
> try `--ignore-scripts`

npm install でエラーになってるので無意味でした

**Comment by TwoSquirrels** [comment]
`NODE_ENV` 環境変数が `"production"` でなくても、
`pnpm install --prod` でなる可能性もあるのでそれも考慮

**Comment by Mogyuchi** [comment]
```json
{
  "scripts": {
    "prepare": "husky install || [ $? = 127 ]"
  }
}
```
が良いのかなと。
