### ISSUE TITLE
[DX]: GitHub Actions、Ubuntu のバージョンを指定する

### ISSUE THREAD

**Issue by Mogyuchi** [uchikoshi-fes/uchikoshi-fes.jp-2022#83]
### 改善対象の事柄

```yaml
runs-on: ubuntu-latest
```

### 期待する挙動

```yaml
runs-on: ubuntu-20.04
```

**Comment by Mogyuchi** [comment]
https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/blob/330616ad5b8d33086070017aa2c9363bd03fff2b/.github/workflows/maintain-quality.yml#L10
変え忘れてるんですよね。。。

**Comment by TwoSquirrels** [comment]
wtf
