### ISSUE TITLE
[Bug]: ページ読み込み時に noindex になってしまう

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2022#93]
### URL

https://uchikoshi-fes.jp/

### 現在の状況

静的 HTML 自体は `<meta>` タグの `robots` が `index,follow` となっているが、
ページをブラウザで読み込んだ際に `noindex,follow` に書き換えられてしまう。

### スクリーンショット

```js
javascript:(()=>{alert([...document.getElementsByTagName("meta")].map(e=>e.outerHTML))})()
```

を実行した様子 ↓

![Screenshot_2022-06-14-15-37-23-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/47352965/173509837-3859b9cc-2a84-4f65-9c7c-f5e7da966c84.jpg)

### 期待する挙動

本番環境にて noindex に書き換えられない。

### OS

Android

### ブラウザ

Chrome

### 補足情報

恐らく next-seo.config.js がページ読み込み時にも動いてしまっている事が原因。

**Comment by TwoSquirrels** [comment]
これかな？
https://github.com/garmeeh/next-seo/issues/420

**Comment by TwoSquirrels** [comment]
やべ、 next-seo のリポジトリにメンション飛んじゃった

**Comment by TwoSquirrels** [comment]
`getStaticProps` を使えばなんとかなりそう

**Comment by Mogyuchi** [comment]
なんのためにこの設定入れてるの？
https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/blob/1c1bb9c0e6b2d98a438eb3104fa09ac5953a3a35/next-seo.config.js#L23-L25

**Comment by TwoSquirrels** [comment]
Cloudflare のプレビューが Google にインデックスされないようにするため

**Comment by Mogyuchi** [comment]
プレビュービルドには `x-robots-tag: noindex` が指定されるので要らないです。
<img width="912" alt="スクリーンショット 2022-06-14 16 49 36" src="https://user-images.githubusercontent.com/69337624/173523073-38f5be31-735d-4db5-bf0d-5e2fdac10f63.png">

**Comment by TwoSquirrels** [comment]
！？！？

**Comment by Mogyuchi** [comment]
それはそう
issue分割するか

**Comment by TwoSquirrels** [comment]
せやな
